theme: jekyll-theme-minimal
logo: https://www.inspireuplift.com/resizer/?image=https://cdn.inspireuplift.com/uploads/images/seller_products/31765/1702976057_Emospongebob.png&width=600&height=600&quality=90&format=auto&fit=pad
title: Nicholas' Bioinformatics Class
