theme: jekyll-theme-minimal
logo: https://w7.pngwing.com/pngs/822/548/png-transparent-spongebob-patrick-patrick-star-spongebob-squarepants-sandy-cheeks-starfish-patrick-039-s-day-animals-fictional-character-star-thumbnail.png
title: Nicholas' Bioinformatics Class
